default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('FLIP_ACCOUNT') }}"
      # User/password auth
      user: "{{ env_var('FLIP_USERNAME') }}"
      password: "{{ env_var('FLIP_PASSWORD') }}"
      role: "{{ env_var('FLIP_ROLE') }}"
      schema: "{{ env_var('FLIP_USERNAME') }}"
      region: "{{ env_var('FLIP_REGION') }}"
      database: "{{ env_var('FLIP_DATABASE') }}"
      warehouse: "{{ env_var('FLIP_WAREHOUSE') }}"
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_community
  config:
    send_anonymous_usage_stats: False